// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUFd3lwY1tVi_Q7QlqeNcVGPESGJC12G0',
    appId: '1:55983653236:web:4711a33cadbe6939f06c21',
    messagingSenderId: '55983653236',
    projectId: 'courtmanager-64e23',
    authDomain: 'courtmanager-64e23.firebaseapp.com',
    storageBucket: 'courtmanager-64e23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgv1pKVwOGsmTzyv-6nqus0B5SyBFoj94',
    appId: '1:55983653236:android:3cdcbe40ca1df06cf06c21',
    messagingSenderId: '55983653236',
    projectId: 'courtmanager-64e23',
    storageBucket: 'courtmanager-64e23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7OmlTYKRTFU_jGEFhxBD4yGRrB5S7dNg',
    appId: '1:55983653236:ios:1b0537f4957aaa29f06c21',
    messagingSenderId: '55983653236',
    projectId: 'courtmanager-64e23',
    storageBucket: 'courtmanager-64e23.firebasestorage.app',
    iosBundleId: 'com.example.courtManager',
  );
}
